Repository commercetools/nimbus, pull requests merged in 2025-06, with the labels that each got.

#160 feat(storybook): add accessibility test configuration to preview sett…
  packages/nimbus/.storybook/preview.tsx
Labels: trivial

#166 refactor(card): update exports to include prefixed component names
  packages/nimbus/src/components/card/card.tsx
Labels: trivial

#170 FCT-1555: change color value of ctviolet.11 step token
  packages/tokens/css/design-tokens.css
  packages/tokens/src/base/tokens.json
  packages/tokens/src/generated/chakra/theme-tokens.ts
  packages/tokens/src/generated/ts/design-tokens.ts
Labels: trivial

#179 refactor(toggle-button-group): update component title and adjust exports
  packages/nimbus/src/components/toggle-button-group/toggle-button-group.mdx
  packages/nimbus/src/components/toggle-button-group/toggle-button-group.tsx
Labels: trivial

#180 refactor(em): remove Em component
  packages/nimbus/src/components/em/em.mdx
  packages/nimbus/src/components/em/em.tsx
  packages/nimbus/src/components/em/index.ts
  packages/nimbus/src/components/index.ts
Labels: trivial

#184 chore(storybook): update to latest v8 version
  packages/nimbus/src/components/form-field/form-field.stories.tsx
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: trivial

#198 chore(nimbus): `Badge` documentation
  apps/docs/public/images/badge/badge-semantic-colors-do.png
  apps/docs/public/images/badge/badge-semantic-colors-dont.png
  apps/docs/public/images/badge/badge-uses-do.png
  apps/docs/public/images/badge/badge-uses-dont.png
  packages/nimbus/src/components/badge/badge.mdx
  packages/nimbus/src/components/toggle-button-group/toggle-button-group.stories.tsx
Labels: documentation

#208 chore(n): create `NumberInput` docs
  apps/docs/public/images/number-input/number-input-do.png
  apps/docs/public/images/number-input/number-input-dont.png
  packages/nimbus/src/components/number-input/number-input.mdx
Labels: documentation

#211 chore(n): create `ComboBox` docs
  apps/docs/public/images/combobox/combobox-do.png
  apps/docs/public/images/combobox/combobox-dont.png
  packages/nimbus/src/components/combobox/combobox.mdx
Labels: documentation, Passes UI/UX review
